# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vigil/clock/v1/clock.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'vigil/clock/v1/clock.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1avigil/clock/v1/clock.proto\x12\x0evigil.clock.v1\"\x8c\x01\n\x0f\x46orecastRequest\x12\x16\n\x06series\x18\x01 \x03(\x01R\x06series\x12\x18\n\x07horizon\x18\x02 \x01(\rR\x07horizon\x12\x1c\n\tquantiles\x18\x03 \x03(\x01R\tquantiles\x12)\n\x10\x63ovariate_future\x18\x04 \x03(\x01R\x0f\x63ovariateFuture\"\x90\x01\n\x10\x46orecastResponse\x12\x14\n\x05point\x18\x01 \x03(\x01R\x05point\x12\'\n\x0fquantile_values\x18\x02 \x03(\x01R\x0equantileValues\x12#\n\rnum_quantiles\x18\x03 \x01(\rR\x0cnumQuantiles\x12\x18\n\x07horizon\x18\x04 \x01(\rR\x07horizon\"\x0f\n\rHealthRequest\"G\n\x0eHealthResponse\x12\x14\n\x05ready\x18\x01 \x01(\x08R\x05ready\x12\x1f\n\x0bstatus_code\x18\x02 \x01(\rR\nstatusCode2\xa9\x01\n\x0f\x46orecastService\x12M\n\x08\x46orecast\x12\x1f.vigil.clock.v1.ForecastRequest\x1a .vigil.clock.v1.ForecastResponse\x12G\n\x06Health\x12\x1d.vigil.clock.v1.HealthRequest\x1a\x1e.vigil.clock.v1.HealthResponseBLZJgithub.com/Abishai95141/Vigil-Dilijens/proto/gen/go/vigil/clock/v1;clockv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vigil.clock.v1.clock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZJgithub.com/Abishai95141/Vigil-Dilijens/proto/gen/go/vigil/clock/v1;clockv1'
  _globals['_FORECASTREQUEST']._serialized_start=47
  _globals['_FORECASTREQUEST']._serialized_end=187
  _globals['_FORECASTRESPONSE']._serialized_start=190
  _globals['_FORECASTRESPONSE']._serialized_end=334
  _globals['_HEALTHREQUEST']._serialized_start=336
  _globals['_HEALTHREQUEST']._serialized_end=351
  _globals['_HEALTHRESPONSE']._serialized_start=353
  _globals['_HEALTHRESPONSE']._serialized_end=424
  _globals['_FORECASTSERVICE']._serialized_start=427
  _globals['_FORECASTSERVICE']._serialized_end=596
# @@protoc_insertion_point(module_scope)
