# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from vigil.clock.v1 import clock_pb2 as vigil_dot_clock_dot_v1_dot_clock__pb2


class ForecastServiceStub:
    """ForecastService is the model-agnostic "clock" (doc 09 §3.1). The model answers
    exactly one question: when does this number cross that number.

    CHARTER INVARIANT (doc 01 §4, techstack §5): this service carries NO string
    fields anywhere. The "model never sees labels, names, units, or graph structure"
    rule becomes a compile-time property — only float arrays, horizon ints, and
    quantile arrays cross this boundary. A conformance test (clock/conformance_test.go)
    reflects over the generated descriptor and FAILS if any field of kind string is
    ever added. Do not add strings to this proto.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Forecast = channel.unary_unary(
                '/vigil.clock.v1.ForecastService/Forecast',
                request_serializer=vigil_dot_clock_dot_v1_dot_clock__pb2.ForecastRequest.SerializeToString,
                response_deserializer=vigil_dot_clock_dot_v1_dot_clock__pb2.ForecastResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/vigil.clock.v1.ForecastService/Health',
                request_serializer=vigil_dot_clock_dot_v1_dot_clock__pb2.HealthRequest.SerializeToString,
                response_deserializer=vigil_dot_clock_dot_v1_dot_clock__pb2.HealthResponse.FromString,
                _registered_method=True)


class ForecastServiceServicer:
    """ForecastService is the model-agnostic "clock" (doc 09 §3.1). The model answers
    exactly one question: when does this number cross that number.

    CHARTER INVARIANT (doc 01 §4, techstack §5): this service carries NO string
    fields anywhere. The "model never sees labels, names, units, or graph structure"
    rule becomes a compile-time property — only float arrays, horizon ints, and
    quantile arrays cross this boundary. A conformance test (clock/conformance_test.go)
    reflects over the generated descriptor and FAILS if any field of kind string is
    ever added. Do not add strings to this proto.
    """

    def Forecast(self, request, context):
        """Forecast projects the shape of one bare, scale-normalized series.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health reports model readiness for the Tier-B degradation panel (doc 14 A13).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ForecastServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Forecast': grpc.unary_unary_rpc_method_handler(
                    servicer.Forecast,
                    request_deserializer=vigil_dot_clock_dot_v1_dot_clock__pb2.ForecastRequest.FromString,
                    response_serializer=vigil_dot_clock_dot_v1_dot_clock__pb2.ForecastResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=vigil_dot_clock_dot_v1_dot_clock__pb2.HealthRequest.FromString,
                    response_serializer=vigil_dot_clock_dot_v1_dot_clock__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vigil.clock.v1.ForecastService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vigil.clock.v1.ForecastService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ForecastService:
    """ForecastService is the model-agnostic "clock" (doc 09 §3.1). The model answers
    exactly one question: when does this number cross that number.

    CHARTER INVARIANT (doc 01 §4, techstack §5): this service carries NO string
    fields anywhere. The "model never sees labels, names, units, or graph structure"
    rule becomes a compile-time property — only float arrays, horizon ints, and
    quantile arrays cross this boundary. A conformance test (clock/conformance_test.go)
    reflects over the generated descriptor and FAILS if any field of kind string is
    ever added. Do not add strings to this proto.
    """

    @staticmethod
    def Forecast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigil.clock.v1.ForecastService/Forecast',
            vigil_dot_clock_dot_v1_dot_clock__pb2.ForecastRequest.SerializeToString,
            vigil_dot_clock_dot_v1_dot_clock__pb2.ForecastResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigil.clock.v1.ForecastService/Health',
            vigil_dot_clock_dot_v1_dot_clock__pb2.HealthRequest.SerializeToString,
            vigil_dot_clock_dot_v1_dot_clock__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
